apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: soc-frontend
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: soc-frontend:latest
