apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soc-demo
commonLabels:
  app: soc-frontend
  app.kubernetes.io/part-of: memoryhub-demo
resources:
  - imagestream.yaml
  - imagestream-sidecar.yaml
  - buildconfig.yaml
  - buildconfig-sidecar.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
