apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-model-cache
  namespace: embedding-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
