apiVersion: v1
kind: Service
metadata:
  name: ms-marco-minilm-l12-v2
  namespace: reranker-model
spec:
  selector:
    app: ms-marco-minilm-l12-v2
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
