"""Project-config scaffolding for `memoryhub config init`.

Pure functions that build a :class:`memoryhub.ProjectConfig` from a set
of choices and render the corresponding `.memoryhub.yaml` and
`.claude/rules/memoryhub-loading.md` files.

The interactive prompting lives in :mod:`memoryhub_cli.main`; everything
in this module is testable without I/O of its own.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import yaml
from memoryhub import (
    CONFIG_FILENAME,
    MemoryLoadingConfig,
    ProjectConfig,
    RetrievalDefaults,
)

# ── Choices captured from the interactive prompt ─────────────────────────────


SessionShape = Literal["focused", "broad", "adaptive"]
LoadingPattern = Literal["eager", "lazy", "lazy_with_rebias", "jit"]
FocusSource = Literal["declared", "directory", "first_turn", "auto"]


@dataclass(frozen=True)
class InitChoices:
    """Answers collected from the interactive prompt.

    Decoupled from :class:`ProjectConfig` so the prompt and the schema
    can evolve independently. ``session_shape`` is captured for the
    rule-file template (it shapes the introductory prose) but maps onto
    the ``memory_loading.mode`` field.
    """

    session_shape: SessionShape
    pattern: LoadingPattern
    focus_source: FocusSource
    cross_domain_contradiction_detection: bool


# ── Defaults that the prompt suggests based on session shape ─────────────────


_PATTERN_FOR_SHAPE: dict[SessionShape, LoadingPattern] = {
    "focused": "lazy",
    "broad": "eager",
    "adaptive": "lazy_with_rebias",
}

_MODE_FOR_SHAPE: dict[SessionShape, Literal["focused", "broad"]] = {
    "focused": "focused",
    "broad": "broad",
    "adaptive": "focused",
}


def suggest_pattern(shape: SessionShape) -> LoadingPattern:
    """Return the recommended pattern for a given session shape."""
    return _PATTERN_FOR_SHAPE[shape]


# ── Schema construction ──────────────────────────────────────────────────────


def build_project_config(choices: InitChoices) -> ProjectConfig:
    """Translate user choices into a :class:`ProjectConfig`.

    The ``session_focus_weight`` and Pattern E knobs use schema defaults;
    the prompt does not surface them in v1 to keep the interaction
    short. Users can edit ``.memoryhub.yaml`` directly to tune them and
    re-run ``memoryhub config regenerate``.
    """
    return ProjectConfig(
        memory_loading=MemoryLoadingConfig(
            mode=_MODE_FOR_SHAPE[choices.session_shape],
            pattern=choices.pattern,
            focus_source=choices.focus_source,
            cross_domain_contradiction_detection=(
                choices.cross_domain_contradiction_detection
            ),
        ),
        retrieval_defaults=RetrievalDefaults(),
    )


# ── YAML serialization ───────────────────────────────────────────────────────


_YAML_HEADER = (
    "# MemoryHub project configuration\n"
    "#\n"
    "# Generated by `memoryhub config init`. Edit by hand and run\n"
    "# `memoryhub config regenerate` to refresh the rule file.\n"
    "#\n"
    "# Schema reference: docs/agent-memory-ergonomics/design.md\n"
    "\n"
)


def render_yaml(config: ProjectConfig) -> str:
    """Serialize a ProjectConfig to YAML with a generator banner."""
    body = yaml.safe_dump(
        config.model_dump(),
        sort_keys=False,
        default_flow_style=False,
    )
    return _YAML_HEADER + body


# ── Rule-file templates ──────────────────────────────────────────────────────
#
# The wording of these templates matters more than the YAML config — they are
# the actual instructions the consuming agent reads. Each template is fully
# self-contained: session start, during-session, memory hygiene, and
# contradiction handling. The pattern-specific session-start and
# during-session sections are the only parts that vary; hygiene and
# contradiction handling are shared.


_RULE_HEADER = """\
# MemoryHub Loading: {pattern_title}

This project uses MemoryHub for persistent, centralized agent memory across
conversations. You MUST use it.

This rule was generated by `memoryhub config init` from `.memoryhub.yaml`.
Re-run `memoryhub config regenerate` after editing the YAML to refresh this
file. Do not hand-edit this file directly — your changes will be overwritten.
"""


_PATTERN_BLOCKS: dict[LoadingPattern, str] = {
    "eager": """\
## At session start

1. Call `register_session(api_key="<your-api-key>")` to authenticate.
2. Immediately call `search_memory(query="", mode="index", max_results=50)`
   to load the full working set as lightweight stubs. The empty query plus
   `mode="index"` returns headers for everything visible to your user.
3. Hold the returned working set in context for the entire session.

## During the session

- When a stub looks load-bearing for the current task, call `read_memory`
  to expand it into full content.
- New writes (your own or another agent's) are NOT pushed automatically.
  If a decision depends on the latest state, call `search_memory` again
  rather than trusting the working set you loaded at session start.
""",
    "lazy": """\
## At session start

Call `register_session(api_key="<your-api-key>")` to authenticate. Do NOT
call `search_memory` yet — your working set is empty until the first user
turn arrives.

## After the first user turn

Derive a 1-2 sentence summary of the user's intent from the opening
message. Call `search_memory(query=<summary>)`. Use the returned memories
as your working set for the session.

## During the session

- Trust your working set. Re-search only when the user explicitly
  references a concept you don't have loaded.
- If the opening turn was vague ("can you take a look at this?"), your
  working set may miss relevant memories. Watch for it and re-search with
  a more specific query as soon as the topic firms up.
""",
    "lazy_with_rebias": """\
## At session start

Call `register_session(api_key="<your-api-key>")` to authenticate. Do NOT
call `search_memory` yet.

## After the first user turn

Derive a 1-2 sentence summary of the user's intent from the opening
message. Call `search_memory(query=<summary>)`. Use the returned memories
as your working set for the session.

## During the session — watch for pivots

A pivot is any of:

1. **Subsystem change** — the user changes topic to a different area of
   the project (e.g., from "deployment" to "UI", or from "MCP server" to
   "SDK").
2. **Unknown concept** — the user references a project-specific term that
   isn't in your working set.
3. **Explicit switch** — the user says "let's switch to...", "now let's
   talk about...", or similar phrasing.

When you detect a pivot, call `search_memory` with a query for the new
topic. **ADD the results to your working set; do not replace it.** The
prior topic may come back later in the same session, and the agent should
not have to re-search for memories it already saw.
""",
    "jit": """\
## At session start

Call `register_session(api_key="<your-api-key>")` to authenticate. Do NOT
call `search_memory`. There is no working set in this pattern.

## During the session

- Call `search_memory` only when you encounter a question whose answer
  might be in memory. Each search is one-shot.
- Triggers that warrant a search: the user asks "what did we decide
  about X?", references a project-specific term you don't recognize, or
  asks for a recommendation that should reflect prior decisions.
- After acting on a search result, let it drop from context once the
  immediate question is answered. Do not accumulate a working set.

This pattern minimizes startup token cost at the price of missing
implicit context. Use it for narrow one-shot tooling sessions.
""",
}


_HYGIENE_BLOCK = """\
## Memory hygiene

- Keep memories concise and self-contained. Another agent should
  understand them without re-loading the conversation that produced them.
- DO write preferences, decisions, architectural choices, tool
  configuration, and workflow patterns. Skip ephemeral things like "user
  asked me to read a file."
- Use `update_memory` (not `write_memory`) to revise an existing entry —
  this preserves version history. Use `write_memory` only for new facts.
- Set weights deliberately: `1.0` for critical policies, `0.8-0.9` for
  strong preferences, `0.5-0.7` for nice-to-know context.
- Add rationale branches via `parent_id` + `branch_type="rationale"` when
  the "why" behind a preference is load-bearing.
- Use the right scope: `user` for personal preferences, `project` for
  project-specific context, `organizational` for team/org patterns,
  `enterprise` for mandated policies.
"""


_CONTRADICTION_ENABLED = """\
## Contradiction handling

When you notice the user's behavior contradicting a memory you have
loaded, call `report_contradiction` with the memory_id and a one-sentence
description of the observed behavior. The server tracks contradiction
counts and surfaces stale memories for review.
"""


_CONTRADICTION_DISABLED = """\
## Contradiction handling

This project runs with `cross_domain_contradiction_detection: false` in
`.memoryhub.yaml`, which means you only catch contradictions for memories
inside your current working set. Memories from other domains will not be
checked — that's a deliberate tradeoff for token efficiency over coverage.

When you DO notice a contradiction with a loaded memory, call
`report_contradiction` with the memory_id and a one-sentence description.
"""


_PATTERN_TITLES: dict[LoadingPattern, str] = {
    "eager": "Eager",
    "lazy": "Lazy",
    "lazy_with_rebias": "Lazy + Rebias on Pivot",
    "jit": "Just-in-Time",
}


def render_rule_file(config: ProjectConfig) -> str:
    """Render the full `.claude/rules/memoryhub-loading.md` for a config."""
    pattern = config.memory_loading.pattern
    pattern_block = _PATTERN_BLOCKS[pattern]
    contradiction_block = (
        _CONTRADICTION_ENABLED
        if config.memory_loading.cross_domain_contradiction_detection
        else _CONTRADICTION_DISABLED
    )
    return "\n".join(
        [
            _RULE_HEADER.format(pattern_title=_PATTERN_TITLES[pattern]),
            pattern_block,
            _HYGIENE_BLOCK,
            contradiction_block,
        ]
    )


# ── Filesystem helpers ───────────────────────────────────────────────────────


@dataclass
class WriteResult:
    """Outcome of writing the project config + rule file to disk."""

    yaml_path: Path
    rule_path: Path
    legacy_backup: Path | None  # set when an old memoryhub-integration.md was moved


LEGACY_RULE_NAME = "memoryhub-integration.md"
GENERATED_RULE_NAME = "memoryhub-loading.md"


def _backup_legacy_rule(rules_dir: Path) -> Path | None:
    """Move any existing memoryhub-integration.md aside to a .bak file.

    Returns the backup path, or None if no legacy file existed. Preserves
    multiple backups by appending a numeric suffix when a .bak already
    exists from an earlier run.
    """
    legacy = rules_dir / LEGACY_RULE_NAME
    if not legacy.exists():
        return None
    backup = legacy.with_suffix(legacy.suffix + ".bak")
    n = 1
    while backup.exists():
        backup = legacy.with_suffix(f"{legacy.suffix}.bak.{n}")
        n += 1
    legacy.rename(backup)
    return backup


def write_init_files(
    config: ProjectConfig,
    project_dir: Path,
    *,
    overwrite: bool = False,
) -> WriteResult:
    """Write both `.memoryhub.yaml` and the generated rule file.

    Used by `memoryhub config init`. The regenerate flow uses
    :func:`rewrite_rule_file` instead so it does not clobber the
    user-edited YAML.

    Raises:
        FileExistsError: If either generated file already exists and
            ``overwrite`` is False. The legacy rule file is always
            backed up (never silently overwritten).
    """
    project_dir = Path(project_dir)
    yaml_path = project_dir / CONFIG_FILENAME
    rules_dir = project_dir / ".claude" / "rules"
    rule_path = rules_dir / GENERATED_RULE_NAME

    if not overwrite:
        for existing in (yaml_path, rule_path):
            if existing.exists():
                raise FileExistsError(
                    f"{existing} already exists. Re-run with --force to overwrite."
                )

    rules_dir.mkdir(parents=True, exist_ok=True)
    legacy_backup = _backup_legacy_rule(rules_dir)

    yaml_path.write_text(render_yaml(config))
    rule_path.write_text(render_rule_file(config))

    return WriteResult(
        yaml_path=yaml_path,
        rule_path=rule_path,
        legacy_backup=legacy_backup,
    )


def rewrite_rule_file(
    config: ProjectConfig,
    project_dir: Path,
) -> WriteResult:
    """Rewrite only the rule file from a config; leave .memoryhub.yaml alone.

    Used by `memoryhub config regenerate` after the user edits the YAML
    by hand. The legacy rule file is still backed up if present.
    """
    project_dir = Path(project_dir)
    yaml_path = project_dir / CONFIG_FILENAME
    rules_dir = project_dir / ".claude" / "rules"
    rule_path = rules_dir / GENERATED_RULE_NAME

    rules_dir.mkdir(parents=True, exist_ok=True)
    legacy_backup = _backup_legacy_rule(rules_dir)

    rule_path.write_text(render_rule_file(config))

    return WriteResult(
        yaml_path=yaml_path,
        rule_path=rule_path,
        legacy_backup=legacy_backup,
    )


__all__ = [
    "InitChoices",
    "SessionShape",
    "LoadingPattern",
    "FocusSource",
    "WriteResult",
    "GENERATED_RULE_NAME",
    "LEGACY_RULE_NAME",
    "build_project_config",
    "render_yaml",
    "render_rule_file",
    "rewrite_rule_file",
    "suggest_pattern",
    "write_init_files",
]
