apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: all-minilm-l6-v2
  namespace: embedding-model
spec:
  to:
    kind: Service
    name: all-minilm-l6-v2
  port:
    targetPort: 8080
  tls:
    termination: edge
