apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: granite-embedding
  namespace: embedding-model
spec:
  to:
    kind: Service
    name: granite-embedding
  port:
    targetPort: 8080
  tls:
    termination: edge
