apiVersion: v1
kind: Service
metadata:
  name: granite-embedding
  namespace: embedding-model
spec:
  selector:
    app: granite-embedding
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
