apiVersion: v1
kind: ServiceAccount
metadata:
  name: memoryhub-minio
  labels:
    app.kubernetes.io/name: memoryhub-minio
    app.kubernetes.io/part-of: memoryhub
    app.kubernetes.io/component: storage
