apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memoryhub-db
resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - configmap-init.yaml
  - statefulset.yaml
  - service.yaml
